version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: ./server
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
  app:
    build: ./client
    command: serve -p 8080 public
    ports:
      - "8080:8080"
    depends_on:
      - api